<script lang="ts">
  import { Table, tableMapperValues, type TableSource } from '@skeletonlabs/skeleton'

  const sourceData = [
    { position: 1, name: 'Arduino Nano', use: 'Name of microcontroller: ATmega328. Architecture: AVR. Operating voltage: 5v. Flash memory: 32k KB (from which 2 KB is occupied by the bootloader). Clock speed of the processor: 16MHz. Number of analog in pins: 8. Number of digital I/O pins: 22 (6 of which are pulse width modulation, which allow analogue signals on digital pins) Dc current per io pin: 40mA. Total power consumption: 19mA. It contains UART (Universal Asynchronous Reciever Transmitter) which lets it communicate with other boards'},
    { position: 2, name: 'IR Sensor', use: 'This sensor includes an IR LED & an IR photodiode. An IR LED is a kind of transmitter that emits IR radiation. This LED looks similar to a standard LED and the radiation which is generated by it is not visible to the human eye. IR photodiodes detect only IR radiation. The IR radiation bounces off of objects and then reflects back into the photodiode. The resistance of the photodiode & the change in output voltage is in proportion to the IR radiation received. This is the IR sensor’s fundamental working principle.'},
  { position: 3, name: 'DC Motor', use: 'A DC motor is an electrical machine that transforms electrical energy into mechanical energy by creating a magnetic field that is powered by direct current. When a DC motor is powered, a magnetic field is created in its stator (the stationary component of the motor). The field attracts and repels magnets on the rotor (the moving component of the motor); this causes the rotor to rotate. To keep the rotor continually rotating, the commutator that is attached to brushes connected to the power source supply current to the motors wire windings. One of the reasons DC motors are preferred over other types of motors is their ability to precisely control their speed, which is a necessity for industrial machinery and robotics. DC motors are able to immediately start, stop, and reverse — an essential factor for controlling our robot.'},
  { position: 4, name: 'Jumper cables', use: 'These cables are used to connect different pieces of hardware to our micro-controller'},
  { position: 5, name: 'L239D Motor Driver', use: 'L293D is a basic motor driver integrated chip (IC) that enables us to drive a DC motor in either direction and also control the speed of the motor. The L293D is a 16 pin IC, with 8 pins on each side, allowing us to control the motor. It means that we can use a single L293D to run up to two DC motors.  L293D consist of two H-bridges (A H-bridge is an electronic circuit that switches the polarity of a voltage applied to a load, thus changing the direction of the motor).'},
  { position: 6, name: 'Chassis', use: '-' },
  { position: 7, name: 'Wheels', use: '-'}
  ];

  const table: TableSource = {
    head: ['Name', 'Use'],
    body: tableMapperValues(sourceData, ['name', 'use'])
  }
</script>

<Table source={table} />
