<script lang="ts">
  import { Table, tableMapperValues, type TableSource } from '@skeletonlabs/skeleton'

  const sourceData = [
    { position: 1, name: 'Arduino Uno', use: 'The Arduino Uno is a micro-controller based on the ATmega328P. It functions as the brain of the robot as it controls the logic. It has 14 digital input/output pins, of which 6 are Pulse Width Modulation (sending an analogue signal through a digital pin). These PWM pins allow us to control the speed of the motors. It features 1Kb of EEPROM (Electronically Erasable Programmable Read Only Memory) which is where the program is stored. ', image: '<img class="w-[100rem] hidden sm:block" src="/arduino.png" />'},
    { position: 2, name: 'IR Sensor', use: 'This sensor includes an IR LED & an IR photodiode. An IR LED is a kind of transmitter that emits IR radiation. This LED looks similar to a standard LED and the radiation which is generated by it is not visible to the human eye. IR photodiodes detect only IR radiation. The IR radiation bounces off of objects and then reflects back into the photodiode. The resistance of the photodiode & the change in output voltage is in proportion to the IR radiation received. This is the IR sensor’s fundamental working principle.', image: '<img class="hidden sm:block" src="/sensor.png" />'},
  { position: 3, name: 'DC Motor', use: 'A DC motor is an electrical machine that transforms electrical energy into mechanical energy by creating a magnetic field that is powered by direct current. When a DC motor is powered, a magnetic field is created in its stator (the stationary component of the motor). The field attracts and repels magnets on the rotor (the moving component of the motor); this causes the rotor to rotate. To keep the rotor continually rotating, the commutator that is attached to brushes connected to the power source supply current to the motors wire windings. One of the reasons DC motors are preferred over other types of motors is their ability to precisely control their speed, which is a necessity for industrial machinery and robotics. DC motors are able to immediately start, stop, and reverse — an essential factor for controlling our robot.', image: '<img class="hidden sm:block" src="/motor.png" />'},
  { position: 4, name: 'Jumper cables', use: 'These cables are used to connect different pieces of hardware to our micro-controller', image: '<img class="hidden sm:block" src="/wires.png" />'},
  { position: 5, name: 'L239D Motor Driver', use: 'L293D is a basic motor driver integrated chip (IC) that enables us to drive a DC motor in either direction and also control the speed of the motor. The L293D is a 16 pin IC, with 8 pins on each side, allowing us to control the motor. It means that we can use a single L293D to run up to two DC motors.  L293D consist of two H-bridges (A H-bridge is an electronic circuit that switches the polarity of a voltage applied to a load, thus changing the direction of the motor).', image: '<img class="hidden sm:block" src="/driver.png" />'},
  { position: 6, name: 'Chassis', use: 'It holds together all the components', image: '<img class="hidden sm:block" src="/chassis.png" />' },
  ];

  const table: TableSource = {
    head: ['Name', '', 'Use'],
    body: tableMapperValues(sourceData, ['name', 'image', 'use'])
  }
</script>

<Table source={table} />
