<script lang="ts">
  import { Accordion, AccordionItem, CodeBlock, Table, tableMapperValues, type TableSource } from '@skeletonlabs/skeleton'

  const sourceData = [
    { position: 1, name: 'Arduino Nano', use: 'Name of microcontroller is ATmega328, Architecture is AVR. Operating voltage 5v. flash memory is 32k KB form which 2 KB is occupied by the bootloader. Clock speed of the processor is 16MHz. number of analog in pins is 8, number of digital I/o pins 22 (6 of which are PWM support, PWM is pulse width modulation it is a powerful technique for controlling analog circuits with a microcontroller’s digital outputs used to control brightness of lights) dc current per io pin is 40mA and total power consumption is 19mA.'},
    { position: 2, name: 'IR Sensor', use: 'The working principle of an infrared sensor is similar to the object detection sensor. This sensor includes an IR LED & an IR Photodiode, so by combining these two can be formed as a photo-coupler otherwise optocoupler. IR LED is one kind of transmitter that emits IR radiations. This LED looks similar to a standard LED and the radiation which is generated by this is not visible to the human eye. Infrared receivers mainly detect the radiation using an infrared transmitter. These infrared receivers are available in photodiodes form. IR Photodiodes are dissimilar as compared with usual photodiodes because they detect simply IR radiation. The infrared photodiode is responsive to the infrared light that is generated through an infrared LED. The resistance of photo-diode & the change in output voltage is in proportion to the infrared light obtained. This is the IR sensor’s fundamental working principle.'},
  { position: 3, name: 'DC Motor', use: 'A DC motor or direct current motor is an electrical machine that transforms electrical energy into mechanical energy by creating a magnetic field that is powered by direct current. When a DC motor is powered, a magnetic field is created in its stator. The field attracts and repels magnets on the rotor; this causes the rotor to rotate. To keep the rotor continually rotating, the commutator that is attached to brushes connected to the power source supply current to the motors wire windings. One of the reasons DC motors are preferred over other types of motors is their ability to precision control their spe ed, which is a necessity for industrial machinery. DC motors are able to immediately start, stop, and reverse—an essential factor for controlling the operation of production equipment.'},
  { position: 4, name: 'Jumper cables', use: 'These cables are used to connect different pieces of hardware to our micro-controller'},
  { position: 5, name: 'L239D Motor Driver', use: 'L293D is a basic motor driver integrated chip (IC) that enables us to drive a DC motor in either direction and also control the speed of the motor. The L293D is a 16 pin IC, with 8 pins on each side, allowing us to control the motor. It means that we can use a single L293D to run up to two DC motors.  L293D consist of two H-bridge (A H-bridge is an electronic circuit that switches the polarity of a voltage applied to a load.) circuit.'},
  { position: 6, name: 'Chassis', use: '-' },
  { position: 7, name: 'Wheels', use: '-'}
  ];

  const table: TableSource = {
    head: ['Name', 'Use'],
    body: tableMapperValues(sourceData, ['name', 'use'])
  }
</script>

<main>
  <h1 class="text-center bg-gradient-to-br from-blue-500 to-cyan-300 bg-clip-text text-transparent box-decoration-clone m-2">Team Curiosity</h1>
  <Accordion>
    <AccordionItem>
      <svelte:fragment slot="summary">Introduction</svelte:fragment>
      <svelte:fragment slot="content">The line following car is a car that follows a black line on white surface. The basic concept of the line following car is that the line is detected using Infra-red sensor and according to the signal received from the sensors, microcontroller decides what movement should follow the car. This line following car uses infra-red sensor that out puts a analog signal according to the light intensity fall on it. Here black surface absorbs light more than the white surface, this is the basic theory of detecting the black line. The states of the photo transitors captured by the comparator and it produce 1 or 0 for the recieving signal. According to the signals recieved by microcontroller(Arduino Nano) is controling the car. For turning the car a certain direction the opposite motor is turned off to allow a turn i.e if the car has to make a left turn the right motor is turned off.</svelte:fragment>
    </AccordionItem>
    <AccordionItem>
      <svelte:fragment slot="summary">Hardware</svelte:fragment>
      <svelte:fragment slot="content">
        <Table source={table} />
      </svelte:fragment>
    </AccordionItem>
    <AccordionItem>
      <svelte:fragment slot="summary">Software</svelte:fragment>
      <svelte:fragment slot="content">
        We are defining all our inputs and outputs
        <CodeBlock language="arduino" code={`#define LftSensr  3
#define RghtSensr 4

#define LftMotrMvmnt_1   9
#define RghtMotrMvmnt_1  7

#define LftMotrMvmnt_2  6
#define RghtMotrMvmnt_2 8`}
        />
        Starting serial monitor, setting pin modes for inputs and outputs
        <CodeBlock language="arduino" code={`void setup() {
  Serial.begin(9600);

  //IR sensor input
  pinMode(LftSensr,  INPUT);
  pinMode(RghtSensr, INPUT);
  //Motor 1
  pinMode(LftMotrMvmnt_1,  OUTPUT);
  pinMode(RghtMotrMvmnt_1, OUTPUT);
  // Motor 2
  pinMode(LftMotrMvmnt_2,  OUTPUT);
  pinMode(RghtMotrMvmnt_2, OUTPUT);

  Serial.println("setup done");
}`} 
        />
          We are storing the values we receive form the sensor into a variable of character data type. The values of the sensor can be of two numbers 1 or 0, In an IR sensor 0 is for object detected and 1 is for object not detected. We found this by printing the values of the sensor in serial monitor(//Console Logs For Debugging).
        <CodeBlock language="arduino" code={`void loop() {
  char LftSnsr, RghtSnsr;

  /* read sensor values /
  LeftSnsr  = digitalRead(LftSnsr);
  RghtSnsr = digitalRead(RghtSnsr);`}
        />
      </svelte:fragment>
    </AccordionItem>
    <AccordionItem>
      <svelte:fragment slot="summary">Simulation</svelte:fragment>
      <svelte:fragment slot="content">
        <iframe src="https://editor.p5js.org/zsaquarian/full/HwMyEBwC5" title="Simulation" class="mx-auto w-full h-96 lg:w-[90rem] lg:h-[45rem]"></iframe>
      </svelte:fragment>
    </AccordionItem>
  </Accordion>
  <div class="absolute bottom-2 right-2">
    <p>By Team Curiosity</p>
    <a href="https://github.com/zsaquarian/">Github</a>
  </div>
</main>
