<script lang="ts">
  import Introduction from '$lib/Introduction.svelte';
	import Software from '$lib/Software.svelte';
import { Accordion, AccordionItem, CodeBlock, Tab, TabGroup, Table, tableMapperValues, type TableSource } from '@skeletonlabs/skeleton'

  const sourceData = [
    { position: 1, name: 'Arduino Nano', use: 'Name of microcontroller is ATmega328, Architecture is AVR. Operating voltage 5v. flash memory is 32k KB form which 2 KB is occupied by the bootloader. Clock speed of the processor is 16MHz. number of analog in pins is 8, number of digital I/o pins 22 (6 of which are PWM support, PWM is pulse width modulation it is a powerful technique for controlling analog circuits with a microcontroller’s digital outputs used to control brightness of lights) dc current per io pin is 40mA and total power consumption is 19mA.'},
    { position: 2, name: 'IR Sensor', use: 'The working principle of an infrared sensor is similar to the object detection sensor. This sensor includes an IR LED & an IR Photodiode, so by combining these two can be formed as a photo-coupler otherwise optocoupler. IR LED is one kind of transmitter that emits IR radiations. This LED looks similar to a standard LED and the radiation which is generated by this is not visible to the human eye. Infrared receivers mainly detect the radiation using an infrared transmitter. These infrared receivers are available in photodiodes form. IR Photodiodes are dissimilar as compared with usual photodiodes because they detect simply IR radiation. The infrared photodiode is responsive to the infrared light that is generated through an infrared LED. The resistance of photo-diode & the change in output voltage is in proportion to the infrared light obtained. This is the IR sensor’s fundamental working principle.'},
  { position: 3, name: 'DC Motor', use: 'A DC motor or direct current motor is an electrical machine that transforms electrical energy into mechanical energy by creating a magnetic field that is powered by direct current. When a DC motor is powered, a magnetic field is created in its stator. The field attracts and repels magnets on the rotor; this causes the rotor to rotate. To keep the rotor continually rotating, the commutator that is attached to brushes connected to the power source supply current to the motors wire windings. One of the reasons DC motors are preferred over other types of motors is their ability to precision control their spe ed, which is a necessity for industrial machinery. DC motors are able to immediately start, stop, and reverse—an essential factor for controlling the operation of production equipment.'},
  { position: 4, name: 'Jumper cables', use: 'These cables are used to connect different pieces of hardware to our micro-controller'},
  { position: 5, name: 'L239D Motor Driver', use: 'L293D is a basic motor driver integrated chip (IC) that enables us to drive a DC motor in either direction and also control the speed of the motor. The L293D is a 16 pin IC, with 8 pins on each side, allowing us to control the motor. It means that we can use a single L293D to run up to two DC motors.  L293D consist of two H-bridge (A H-bridge is an electronic circuit that switches the polarity of a voltage applied to a load.) circuit.'},
  { position: 6, name: 'Chassis', use: '-' },
  { position: 7, name: 'Wheels', use: '-'}
  ];

  const table: TableSource = {
    head: ['Name', 'Use'],
    body: tableMapperValues(sourceData, ['name', 'use'])
  }

  let tabSet = 0;
</script>

<main>
  <h1 class="text-center bg-gradient-to-br from-blue-500 to-cyan-300 bg-clip-text text-transparent box-decoration-clone m-2">Team Curiosity</h1>
  <TabGroup>
    <Tab bind:group={tabSet} name="intro" value={0}>Introduction</Tab>
    <Tab bind:group={tabSet} name="hardware" value={1}>Hardware</Tab>
    <Tab bind:group={tabSet} name="software" value={2}>Software</Tab>
    <Tab bind:group={tabSet} name="software" value={3}>Simulation</Tab>
    <svelte:fragment slot="panel">
      {#if tabSet === 0}
        <Introduction />
      {:else if tabSet === 1}
        <Table source={table} />
      {:else if tabSet === 2}
        <Software />
      {:else if tabSet === 3}
        <iframe src="https://editor.p5js.org/zsaquarian/full/HwMyEBwC5" title="Simulation" class="mx-auto w-full h-96 lg:w-[90rem] lg:h-[45rem]"></iframe>
      {/if}
    </svelte:fragment>
  </TabGroup>
  <div class="absolute bottom-2 right-2">
    <p>By Team Curiosity</p>
    <a href="https://github.com/zsaquarian/">Github</a>
  </div>
</main>
